//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQMusicBathDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public string Name { get; set; }
        public string Author { get; set; }
        public string Album { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Mood { get; set; }
        public string Type { get; set; }
        public int SongID { get; set; }
    }
}
